# Generated by Django 5.0.14 on 2026-09-21 04:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org", "0002_remove_affectationresponsable_ecole_id_ecole_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type_equipement", models.CharField(max_length=100)),
                ("total", models.IntegerField(default=0)),
                ("fonctionnel", models.IntegerField(default=0)),
                ("a_reparer", models.IntegerField(default=0)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "ecole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipements",
                        to="org.ecole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Équipement",
                "verbose_name_plural": "Équipements",
                "db_table": '"trv"."equipement"',
                "ordering": ["ecole", "type_equipement"],
            },
        ),
        migrations.AddConstraint(
            model_name="equipement",
            constraint=models.UniqueConstraint(
                fields=("ecole", "type_equipement"), name="uq_equipement_ecole_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipement",
            constraint=models.CheckConstraint(
                check=models.Q(("fonctionnel__lte", models.F("total"))),
                name="chk_equipement_total_coherent",
            ),
        ),
    ]
