# Generated by Django 5.0.14 on 2026-09-21 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0002_remove_affectationresponsable_ecole_id_ecole_and_more"),
        ("trv", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("sujet", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "ecole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages_contact",
                        to="org.ecole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "db_table": '"trv"."message_contact"',
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("infrastructure", "Infrastructure"),
                            ("pedagogique", "Pédagogique"),
                            ("securite", "Sécurité"),
                            ("administratif", "Administratif"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "origine",
                    models.CharField(
                        choices=[("citoyen", "Citoyen"), ("interne", "Interne")],
                        default="interne",
                        max_length=10,
                    ),
                ),
                ("nom_declarant", models.CharField(blank=True, max_length=150)),
                ("telephone_declarant", models.CharField(blank=True, max_length=20)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("en_cours", "En cours"),
                            ("traite", "Traité"),
                            ("rejete", "Rejeté"),
                        ],
                        default="nouveau",
                        max_length=15,
                    ),
                ),
                ("commentaire_traitement", models.TextField(blank=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signalements_effectues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ecole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signalements",
                        to="org.ecole",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signalements_traites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signalement",
                "verbose_name_plural": "Signalements",
                "db_table": '"trv"."signalement"',
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_prevue", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("realisee", "Réalisée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=15,
                    ),
                ),
                ("date_realisation", models.DateField(blank=True, null=True)),
                ("rapport", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "ecole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="org.ecole",
                    ),
                ),
                (
                    "inspecteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections_assignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "planifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections_planifiees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signalement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="trv.signalement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection",
                "verbose_name_plural": "Inspections",
                "db_table": '"trv"."inspection"',
                "ordering": ["-date_prevue"],
            },
        ),
    ]
