# Generated by Django 5.0.14 on 2026-09-20 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifiant', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(max_length=30)),
                ('mot_de_passe_provisoire', models.BooleanField(default=True)),
                ('profil', models.CharField(choices=[('citoyen', 'Citoyen'), ('enseignant', 'Enseignant'), ('directeur_ecole', "Directeur d'école"), ('dse', 'Directeur Sous-Préfectoral'), ('dce', 'Directeur Communal'), ('dpe', 'Directeur Préfectoral'), ('ir', 'Inspecteur Régional'), ('dge', "Directeur Général de l'Éducation"), ('super_admin', 'Super Admin'), ('ministre', 'Ministre'), ('cabinet', 'Cabinet')], max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_attente_activation', "En attente d'activation"), ('suspendu', 'Suspendu'), ('revoque', 'Révoqué')], default='en_attente_activation', max_length=25)),
                ('nom', models.CharField(max_length=120)),
                ('prenoms', models.CharField(max_length=180)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('otp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('otp_actif', models.BooleanField(default=False)),
                ('tentatives_echec', models.SmallIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': '"usr"."utilisateur"',
                'ordering': ['nom', 'prenoms'],
            },
        ),
    ]
