# Generated by Django 5.0.14 on 2026-09-21 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0002_remove_affectationresponsable_ecole_id_ecole_and_more"),
        ("ref", "0004_seed_cycles_classes"),
        ("usr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matricule", models.CharField(blank=True, max_length=20, unique=True)),
                ("matiere_principale", models.CharField(blank=True, max_length=100)),
                (
                    "statut_enseignant",
                    models.CharField(
                        choices=[
                            ("titulaire", "Titulaire"),
                            ("contractuel", "Contractuel"),
                            ("stagiaire", "Stagiaire"),
                            ("vacataire", "Vacataire"),
                            ("retraite", "Retraité"),
                        ],
                        default="titulaire",
                        max_length=20,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiche_enseignant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enseignant",
                "verbose_name_plural": "Enseignants",
                "db_table": '"usr"."enseignant"',
                "ordering": ["utilisateur__nom"],
            },
        ),
        migrations.CreateModel(
            name="InterventionEnseignant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matiere", models.CharField(max_length=100)),
                (
                    "volume_horaire_hebdo",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "annee_academique",
                    models.CharField(default="2026-2027", max_length=9),
                ),
                ("actif", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interventions_enseignants",
                        to="ref.classe",
                    ),
                ),
                (
                    "ecole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interventions_enseignants",
                        to="org.ecole",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="usr.enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention d'un enseignant",
                "verbose_name_plural": "Interventions des enseignants",
                "db_table": '"usr"."intervention_enseignant"',
                "ordering": ["-cree_le"],
            },
        ),
        migrations.AddConstraint(
            model_name="interventionenseignant",
            constraint=models.UniqueConstraint(
                fields=("enseignant", "ecole", "classe", "matiere", "annee_academique"),
                name="uq_intervention_enseignant",
            ),
        ),
    ]
