# Generated by Django 5.0.14 on 2026-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr", "0002_enseignant_interventionenseignant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="otp_expire_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
