# Generated by Django 5.0.14 on 2026-09-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr", "0003_utilisateur_otp_expire_le"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interventionenseignant",
            name="matiere",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
