# Generated by Django 5.0.14 on 2026-09-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr", "0004_alter_interventionenseignant_matiere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enseignant",
            name="matiere_principale",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
