# Generated by Django 5.0.14 on 2026-09-21 04:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org", "0002_remove_affectationresponsable_ecole_id_ecole_and_more"),
        ("ref", "0004_seed_cycles_classes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eleve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matricule", models.CharField(blank=True, max_length=30, unique=True)),
                ("nom", models.CharField(max_length=120)),
                ("prenoms", models.CharField(max_length=180)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("lieu_naissance", models.CharField(blank=True, max_length=120)),
                ("photo_url", models.TextField(blank=True)),
                (
                    "annee_academique",
                    models.CharField(default="2026-2027", max_length=9),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("transfere", "Transféré"),
                            ("diplome", "Diplômé"),
                            ("abandon", "Abandon"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eleves",
                        to="ref.classe",
                    ),
                ),
                (
                    "ecole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eleves",
                        to="org.ecole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élève",
                "verbose_name_plural": "Élèves",
                "db_table": '"ped"."eleve"',
                "ordering": ["nom", "prenoms"],
            },
        ),
        migrations.CreateModel(
            name="Filiation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lien",
                    models.CharField(
                        choices=[
                            ("pere", "Père"),
                            ("mere", "Mère"),
                            ("tuteur", "Tuteur"),
                            ("frere_soeur", "Frère / Sœur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nom_complet", models.CharField(max_length=200)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("urgence", models.BooleanField(default=False)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filiations",
                        to="ped.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filiation",
                "verbose_name_plural": "Filiations",
                "db_table": '"ped"."filiation"',
                "ordering": ["eleve", "lien"],
            },
        ),
        migrations.AddIndex(
            model_name="eleve",
            index=models.Index(
                fields=["ecole", "classe"], name="idx_eleve_ecole_classe"
            ),
        ),
    ]
