# Generated by Django 5.0.14 on 2026-09-24 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ped", "0001_initial"),
        ("ref", "0008_alter_prefecture_code_alter_region_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliberation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(default="2026-2027", max_length=9),
                ),
                (
                    "moyenne_generale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("admis", "Admis"),
                            ("redoublant", "Redoublant"),
                            ("examen_national_requis", "Examen national requis"),
                            ("exclu", "Exclu"),
                        ],
                        max_length=25,
                    ),
                ),
                ("motif", models.TextField(blank=True)),
                ("date_deliberation", models.DateField(auto_now_add=True)),
                (
                    "decide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliberations_decidees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliberations",
                        to="ped.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Délibération",
                "verbose_name_plural": "Délibérations",
                "db_table": '"ped"."deliberation"',
                "ordering": ["-annee_academique"],
            },
        ),
        migrations.CreateModel(
            name="InscriptionExamen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_examen",
                    models.CharField(
                        choices=[("CEP", "CEP"), ("BEPC", "BEPC"), ("BAC", "BAC")],
                        max_length=10,
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(default="2026-2027", max_length=9),
                ),
                (
                    "numero_candidat",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "resultat",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("admis", "Admis"),
                            ("echec", "Échec"),
                        ],
                        default="en_attente",
                        max_length=15,
                    ),
                ),
                (
                    "moyenne_examen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("date_resultat", models.DateField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_examens",
                        to="ped.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription à un examen",
                "verbose_name_plural": "Inscriptions aux examens",
                "db_table": '"ped"."inscription_examen"',
                "ordering": ["-annee_academique"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matiere", models.CharField(max_length=100)),
                (
                    "trimestre",
                    models.CharField(
                        choices=[
                            ("T1", "1er trimestre"),
                            ("T2", "2e trimestre"),
                            ("T3", "3e trimestre"),
                        ],
                        max_length=2,
                    ),
                ),
                ("type_evaluation", models.CharField(default="Devoir", max_length=60)),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=4)),
                ("verrouille", models.BooleanField(default=False)),
                (
                    "annee_academique",
                    models.CharField(default="2026-2027", max_length=9),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="ped.eleve",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_saisies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "db_table": '"ped"."note"',
                "ordering": ["-annee_academique", "trimestre", "matiere"],
            },
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matiere", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("present", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presences",
                        to="ref.classe",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="ped.eleve",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presences_enregistrees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
                "db_table": '"ped"."presence"',
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="deliberation",
            constraint=models.UniqueConstraint(
                fields=("eleve", "annee_academique"), name="uq_deliberation_eleve_annee"
            ),
        ),
        migrations.AddConstraint(
            model_name="inscriptionexamen",
            constraint=models.UniqueConstraint(
                fields=("eleve", "type_examen", "annee_academique"),
                name="uq_inscription_eleve_examen_annee",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["eleve", "annee_academique", "trimestre"],
                name="idx_note_eleve_periode",
            ),
        ),
        migrations.AddConstraint(
            model_name="presence",
            constraint=models.UniqueConstraint(
                fields=("eleve", "classe", "matiere", "date"),
                name="uq_presence_eleve_classe_matiere_date",
            ),
        ),
    ]
