# Generated by Django 5.0.14 on 2026-09-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ped", "0003_note_uq_note_eleve_matiere_trimestre_evaluation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eleve",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="eleve",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="eleves/photos/"),
        ),
    ]
