# Generated by Django 5.0.14 on 2026-09-21 01:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametreSysteme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cle", models.CharField(max_length=100, unique=True)),
                ("valeur", models.TextField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètre système",
                "verbose_name_plural": "Paramètres système",
                "ordering": ["cle"],
            },
        ),
    ]
