# Generated by Django 5.0.14 on 2026-09-21 01:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ref", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AffectationResponsable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "profil",
                    models.CharField(
                        choices=[
                            ("citoyen", "Citoyen"),
                            ("enseignant", "Enseignant"),
                            ("directeur_ecole", "Directeur d'école"),
                            ("dse", "Directeur Sous-Préfectoral"),
                            ("dce", "Directeur Communal"),
                            ("dpe", "Directeur Préfectoral"),
                            ("ir", "Inspecteur Régional"),
                            ("dge", "Directeur Général de l'Éducation"),
                            ("super_admin", "Super Admin"),
                            ("ministre", "Ministre"),
                            ("cabinet", "Cabinet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ecole_id", models.UUIDField(blank=True, null=True)),
                (
                    "date_debut",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("actif", "Actif"), ("inactif", "Inactif")],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("motif", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "affecte_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affectations_realisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations",
                        to="ref.commune",
                    ),
                ),
                (
                    "prefecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations",
                        to="ref.prefecture",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations",
                        to="ref.region",
                    ),
                ),
                (
                    "sous_prefecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations",
                        to="ref.sousprefecture",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation d'un responsable",
                "verbose_name_plural": "Affectations des responsables",
                "db_table": '"org"."affectation_responsable"',
                "ordering": ["-date_debut"],
            },
        ),
        migrations.AddConstraint(
            model_name="affectationresponsable",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_fin__isnull", True), ("statut", "actif")),
                fields=("utilisateur",),
                name="uq_affectation_active_par_utilisateur",
            ),
        ),
        migrations.AddConstraint(
            model_name="affectationresponsable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("commune_id__isnull", True),
                        ("ecole_id__isnull", True),
                        ("prefecture_id__isnull", True),
                        ("profil", "dse"),
                        ("region_id__isnull", True),
                        ("sous_prefecture_id__isnull", False),
                    ),
                    models.Q(
                        ("commune_id__isnull", False),
                        ("ecole_id__isnull", True),
                        ("prefecture_id__isnull", True),
                        ("profil", "dce"),
                        ("region_id__isnull", True),
                        ("sous_prefecture_id__isnull", True),
                    ),
                    models.Q(
                        ("commune_id__isnull", True),
                        ("ecole_id__isnull", True),
                        ("prefecture_id__isnull", False),
                        ("profil", "dpe"),
                        ("region_id__isnull", True),
                        ("sous_prefecture_id__isnull", True),
                    ),
                    models.Q(
                        ("commune_id__isnull", True),
                        ("ecole_id__isnull", True),
                        ("prefecture_id__isnull", True),
                        ("profil", "ir"),
                        ("region_id__isnull", False),
                        ("sous_prefecture_id__isnull", True),
                    ),
                    models.Q(
                        ("commune_id__isnull", True),
                        ("ecole_id__isnull", False),
                        ("prefecture_id__isnull", True),
                        ("profil", "directeur_ecole"),
                        ("region_id__isnull", True),
                        ("sous_prefecture_id__isnull", True),
                    ),
                    models.Q(
                        ("commune_id__isnull", True),
                        ("ecole_id__isnull", True),
                        ("prefecture_id__isnull", True),
                        ("profil__in", ["super_admin", "ministre", "cabinet", "dge"]),
                        ("region_id__isnull", True),
                        ("sous_prefecture_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chk_affectation_perimetre",
            ),
        ),
    ]
