# Generated by Django 5.0.14 on 2026-09-21 04:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0001_initial"),
        ("ref", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affectationresponsable",
            name="ecole_id",
        ),
        migrations.CreateModel(
            name="Ecole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_ecole",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "schema_identification",
                    models.CharField(
                        choices=[("A", "Sous-préfecture"), ("B", "Quartier")],
                        max_length=1,
                    ),
                ),
                (
                    "type_ecole",
                    models.CharField(
                        choices=[
                            ("publique", "Publique"),
                            ("privee", "Privée"),
                            ("communautaire", "Communautaire"),
                            ("franco_arabe", "Franco-arabe"),
                            ("confessionnelle", "Confessionnelle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "langue_enseignement",
                    models.CharField(
                        choices=[
                            ("francais", "Français"),
                            ("arabe", "Arabe"),
                            ("francais_arabe", "Français-Arabe"),
                            ("bilingue", "Bilingue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("annee_creation", models.SmallIntegerField(blank=True, null=True)),
                (
                    "coordonnees_gps",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("adresse", models.TextField(blank=True)),
                ("capacite_eleves", models.IntegerField(default=0)),
                ("nombre_salles", models.IntegerField(default=0)),
                ("nombre_salles_fonctionnelles", models.IntegerField(default=0)),
                ("nombre_enseignants", models.IntegerField(default=0)),
                ("nombre_eleves", models.IntegerField(default=0)),
                ("nombre_eleves_filles", models.IntegerField(default=0)),
                ("nombre_eleves_garcons", models.IntegerField(default=0)),
                (
                    "etat_general",
                    models.CharField(
                        choices=[
                            ("conforme", "Conforme"),
                            ("a_renover", "À rénover"),
                            ("critique", "Critique"),
                        ],
                        default="conforme",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "statut_ouverture",
                    models.CharField(
                        choices=[
                            ("ouverte", "Ouverte"),
                            ("fermee", "Fermée"),
                            ("suspendue", "Suspendue"),
                        ],
                        default="ouverte",
                        max_length=20,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecoles",
                        to="ref.commune",
                    ),
                ),
                (
                    "directeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecoles_dirigees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prefecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecoles",
                        to="ref.prefecture",
                    ),
                ),
                (
                    "quartier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecoles",
                        to="ref.quartier",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecoles",
                        to="ref.region",
                    ),
                ),
                (
                    "sous_prefecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecoles",
                        to="ref.sousprefecture",
                    ),
                ),
            ],
            options={
                "verbose_name": "École",
                "verbose_name_plural": "Écoles",
                "db_table": '"org"."ecole"',
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="affectationresponsable",
            name="ecole",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="affectations",
                to="org.ecole",
            ),
        ),
        migrations.AddConstraint(
            model_name="ecole",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("quartier_id__isnull", True),
                        ("schema_identification", "A"),
                        ("sous_prefecture_id__isnull", False),
                    ),
                    models.Q(
                        ("quartier_id__isnull", False),
                        ("schema_identification", "B"),
                        ("sous_prefecture_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chk_ecole_schema",
            ),
        ),
    ]
