# Generated by Django 5.0.14 on 2026-09-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0002_remove_affectationresponsable_ecole_id_ecole_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecole",
            name="langue_enseignement",
            field=models.CharField(
                choices=[
                    ("francais", "Français"),
                    ("arabe", "Arabe"),
                    ("francais_arabe", "Français-Arabe"),
                    ("bilingue", "Bilingue"),
                    ("anglais", "Anglais"),
                ],
                max_length=20,
            ),
        ),
    ]
