# Generated by Django 5.0.14 on 2026-09-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0003_alter_ecole_langue_enseignement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecole",
            name="type_ecole",
            field=models.CharField(
                choices=[("publique", "Publique"), ("privee", "Privée")], max_length=20
            ),
        ),
    ]
