# Generated by Django 5.0.14 on 2026-09-20 23:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^GN-[A-Z]{3}-P-[A-Z0-9]{2,4}$', 'Code préfecture invalide (format attendu : GN-XXX-P-XXXX)')])),
                ('nom', models.CharField(max_length=120)),
                ('chef_lieu', models.CharField(blank=True, max_length=120, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Préfecture',
                'verbose_name_plural': 'Préfectures',
                'db_table': '"ref"."prefecture"',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^GN-[A-Z]{3}$', 'Code région invalide (format attendu : GN-XXX)')])),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('type_zone', models.CharField(default='region', max_length=30)),
                ('chef_lieu', models.CharField(blank=True, max_length=120, null=True)),
                ('nombre_prefectures', models.IntegerField(default=0)),
                ('nombre_communes', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'db_table': '"ref"."region"',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SousPrefecture',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^GN-[A-Z]{3}-SP-[A-Z0-9]{2,5}$', 'Code sous-préfecture invalide (format attendu : GN-XXX-SP-XXXXX)')])),
                ('nom', models.CharField(max_length=120)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('en_attente', 'En attente de DSE'), ('suspendue', 'Suspendue')], default='en_attente', max_length=20)),
                ('nombre_ecoles', models.IntegerField(default=0)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sous-préfecture',
                'verbose_name_plural': 'Sous-préfectures',
                'db_table': '"ref"."sous_prefecture"',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^GN-[A-Z]{3}-C-[A-Z0-9]{2,4}$', 'Code commune invalide (format attendu : GN-XXX-C-XXXX)')])),
                ('nom', models.CharField(max_length=120)),
                ('type_commune', models.CharField(default='urbaine', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='ref.prefecture')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'db_table': '"ref"."commune"',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^GN-[A-Z]{3}-Q-[A-Z0-9]{2,5}$', 'Code quartier invalide (format attendu : GN-XXX-Q-XXXXX)')])),
                ('nom', models.CharField(max_length=120)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('en_attente', 'En attente de DSE'), ('suspendue', 'Suspendue')], default='active', max_length=20)),
                ('nombre_ecoles', models.IntegerField(default=0)),
                ('observation', models.TextField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartiers', to='ref.commune')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'db_table': '"ref"."quartier"',
                'ordering': ['nom'],
            },
        ),
    ]
