# Generated by Django 5.0.14 on 2026-09-20 23:34

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ref', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quartier',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartiers_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prefectures', to='ref.region'),
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='ref.region'),
        ),
        migrations.AddField(
            model_name='sousprefecture',
            name='creee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_prefectures_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sousprefecture',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sous_prefectures', to='ref.prefecture'),
        ),
        migrations.AddIndex(
            model_name='quartier',
            index=models.Index(fields=['statut'], name='idx_quartier_statut'),
        ),
        migrations.AddIndex(
            model_name='quartier',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='idx_quartier_nom_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='quartier',
            constraint=models.UniqueConstraint(fields=('commune', 'nom'), name='uq_quartier_commune_nom'),
        ),
        migrations.AddIndex(
            model_name='prefecture',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='idx_prefecture_nom_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='prefecture',
            constraint=models.UniqueConstraint(fields=('region', 'nom'), name='uq_prefecture_region_nom'),
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('region', 'nom'), name='uq_commune_region_nom'),
        ),
        migrations.AddIndex(
            model_name='sousprefecture',
            index=models.Index(fields=['statut'], name='idx_sous_prefecture_statut'),
        ),
        migrations.AddIndex(
            model_name='sousprefecture',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='idx_sous_prefecture_nom_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='sousprefecture',
            constraint=models.UniqueConstraint(fields=('prefecture', 'nom'), name='uq_sous_prefecture_prefecture_nom'),
        ),
    ]
