# Generated by Django 5.0.14 on 2026-09-21 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("primaire", "Primaire"),
                            ("college", "Collège"),
                            ("lycee", "Lycée"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("libelle", models.CharField(max_length=60)),
                ("duree_annees", models.SmallIntegerField()),
                ("ordre", models.SmallIntegerField()),
                (
                    "examen_fin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CEP", "Certificat d'Études Primaires"),
                            ("BEPC", "Brevet d'Études du Premier Cycle"),
                            ("BAC", "Baccalauréat"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cycle",
                "verbose_name_plural": "Cycles",
                "db_table": '"ref"."cycle"',
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("libelle", models.CharField(max_length=60)),
                ("niveau", models.SmallIntegerField()),
                ("est_classe_fin", models.BooleanField(default=False)),
                ("ordre", models.SmallIntegerField()),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="ref.cycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "db_table": '"ref"."classe"',
                "ordering": ["ordre"],
            },
        ),
    ]
