# Generated by Django 5.0.14 on 2026-09-24 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0004_seed_cycles_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^GN-[A-Z]{3}-C-[A-Z0-9]{2,4}$",
                        "Code commune invalide (format attendu : GN-XXX-C-XXXX)",
                    )
                ],
            ),
        ),
    ]
