# Generated by Django 5.0.14 on 2026-09-24 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0005_alter_commune_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quartier",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=25,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^GN-[A-Z]{3}-[A-Z]{3}-[A-Z0-9]{2,5}$",
                        "Code quartier invalide (format attendu : GN-XXX-XXX-XXXXX)",
                    )
                ],
            ),
        ),
    ]
