# Generated by Django 5.0.14 on 2026-09-24 16:10

from django.db import migrations, models

# Quartier réutilisait le statut à 3 valeurs de SousPrefecture (Active/En
# attente de DSE/Suspendue) alors que le dossier (§9) n'en prévoit que 2 pour
# un quartier — DSE est un rôle sous-préfectoral, sans rapport avec un
# quartier (schéma B). Remappe les valeurs existantes avant de restreindre
# les choix du champ : "en_attente" n'a jamais eu de sens ici, traité comme
# "actif" (état normal, cohérent avec 198 des 200 quartiers déjà "active").
REMAPPAGE = {"active": "actif", "en_attente": "actif", "suspendue": "suspendu"}


def remapper_statuts(apps, schema_editor):
    Quartier = apps.get_model("ref", "Quartier")
    for ancien, nouveau in REMAPPAGE.items():
        Quartier.objects.filter(statut=ancien).update(statut=nouveau)


def remapper_statuts_arriere(apps, schema_editor):
    Quartier = apps.get_model("ref", "Quartier")
    Quartier.objects.filter(statut="actif").update(statut="active")
    Quartier.objects.filter(statut="suspendu").update(statut="suspendue")


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0006_alter_quartier_code"),
    ]

    operations = [
        migrations.RunPython(remapper_statuts, remapper_statuts_arriere),
        migrations.AlterField(
            model_name="quartier",
            name="statut",
            field=models.CharField(
                choices=[("actif", "Actif"), ("suspendu", "Suspendu")],
                default="actif",
                max_length=20,
            ),
        ),
    ]
