# Generated by Django 5.0.14 on 2026-09-24 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0007_alter_quartier_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefecture",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^GN-[A-Z]{3}-P-[A-Z0-9]{2,4}$",
                        "Code préfecture invalide (format attendu : GN-XXX-P-XXXX)",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^GN-[A-Z]{3}$",
                        "Code région invalide (format attendu : GN-XXX)",
                    )
                ],
            ),
        ),
    ]
