# Generated by Django 5.0.14 on 2026-09-21 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalActivite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("cible_type", models.CharField(blank=True, max_length=100)),
                ("cible_id", models.CharField(blank=True, max_length=64)),
                ("detail", models.TextField(blank=True)),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                (
                    "acteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_journal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée du journal d'activité",
                "verbose_name_plural": "Journal d'activité",
                "db_table": '"aud"."journal_activite"',
                "ordering": ["-horodatage"],
                "indexes": [
                    models.Index(fields=["-horodatage"], name="idx_journal_horodatage"),
                    models.Index(fields=["action"], name="idx_journal_action"),
                ],
            },
        ),
    ]
